const MEETINGS = [
    {
        id: "2025-09-24-kickoff",
        type: "brief",
        title: "Kick-off meeting",
        date: "2025-09-24",
        startTime: "15:00",
        endTime: "16:00",
        location: "PwC Offices",
        recorder: "Cyril Beňačka",
        attendees: [
            "Cyril Beňačka",
            "Matúš Bednařík",
            "Alexander Hulla",
            "Adam Jánoš",
            "Adam Kňaze",
            "Júlia Miklošovičová",
            "Patrícia Torok",
        ],
        agenda: [
            { topic: "Špecifikácia zadania", summary: "Prejsť s vedúcimi zadanie a vyriešiť nejasnosti." },
            { topic: "Organizácia projektu", summary: "Dohodnúť sa na nasledujúcom postupe a začiatku práce." },
        ],
        decisions: [
            "Použijeme Jiru na projektové plánovanie a GitHub pre správu kódov.",
            "Budeme využívať agilný vývoj.",
            "Dĺžka sprintu: 2 týždne.",
        ],
        actions: [
            { task: "Založiť prostredie na organizáciu projektového plánovania a projekt v ňom", owner: "Cyril", due: "2025-09-29", status: "done" },
            { task: "Vytvoriť kanál v MS teams na komunikáciu s vedúcimi", owner: "Cyril", due: "2025-09-29", status: "done" },
            { task: "Dodať vzorové dokumenty", owner: "Patrícia", due: "2025-10-08", status: "done" },
            { task: "Vytvoriť WWW stránku s dokumenáciou a zápisnicami", owner: "Cyril", due: "2025-10-10", status: "done" },
            { task: "Návrh technologického stacku pre vývoj AI časti", owner: "Martin, Matúš", due: "2025-10-17", status: "done" },
            { task: "Návrh technologického stacku pre vývoj backendu", owner: "Adam J.", due: "2025-10-17", status: "done" },
            { task: "Návrh technologického stacku pre vývoj frontendu", owner: "Alexander", due: "2025-10-17", status: "done" },
        ],
        previousTasksReview: [],
    },
    {
        id: "2025-10-08-vzorove-dokumenty",
        type: "brief",
        title: "Vzorové dokumenty",
        date: "2025-10-08",
        startTime: "14:15",
        endTime: "14:45",
        location: "MS Teams",
        recorder: "Cyril Beňačka",
        attendees: [
            "Cyril Beňačka",
            "Matúš Bednařík",
            "Patrícia Torok",
        ],
        agenda: [
            { topic: "Vzorové dokumenty", summary: "Prevziať vzorové dokumenty od vedúcich." },
        ],
        decisions: [
            "Prevzaté dokumenty budeme musieť manuálne analyzovať a uistiť sa, že sú jedného typu. Následne ich rozdelíme do podskupín podľa štruktúry ich obsahu.",
        ],
        actions: [
            { task: "Analyzovať vzorové dokumenty", owner: "Martin, Matúš, Alex, Adam", due: "2025-10-10", status: "done" },
        ],
        previousTasksReview: [
            { owner: "Cyril", task: "Vytvoriť WWW stránku s dokumenáciou a zápisnicami", status: "done", notes: "Nasadené na VPS." },
            { owner: "Cyril", task: "Vytvoriť kanál v MS teams na komunikáciu s vedúcimi", status: "done", notes: "Vytvorený kanál v MS Teams, overili sme, že všetci majú prístup." },
            { owner: "Patrícia", task: "Dodať vzorové dokumenty", status: "done", notes: "Dodaných 11 dokumentov." },
            { owner: "Cyril", task: "Vytvoriť WWW stránku s dokumenáciou a zápisnicami", status: "in-progress", notes: "Čiastočná implementácia, nasadená bude keď bude v použiteľnom stave." },
            { owner: "Matúš, Martin", task: "Návrh technologického stacku pre vývoj AI časti", status: "in-progress" },
            { owner: "Adam J.", task: "Návrh technologického stacku pre vývoj backendu", status: "done", notes: "Backend bude vyvíjaný v Pythone, konkrétne FastAPI, kvôli jednoduchému prepojeniu s AI komponentami." },
            { owner: "Alexander", task: "Návrh technologického stacku pre vývoj frontendu", status: "in-progress" },
        ],
    },
    {
        id: "2025-10-10-analyza-dokumentov",
        type: "brief",
        title: "Analýza dokumentov",
        date: "2025-10-10",
        startTime: "11:30",
        endTime: "13:00",
        location: "Unispace FEI STU + Discord",
        recorder: "Cyril Beňačka",
        attendees: [
            "Martin Bartoš",
            "Cyril Beňačka",
            "Matúš Bednařík",
            "Alexander Hulla",
        ],
        agenda: [
            { topic: "Analýza dokumentov", summary: "Prejsť štruktúru vzorových dokumentov." },
            { topic: "Organizácia projektu", summary: "Navrhnúť nasledujúci postup vývoja." },
        ],
        decisions: [
            "Dospeli sme k záveru, že ide o jeden typ dokumentov.",
            "Našli sme 2 základné skupiny: OVS - obchodná verejná súťaž, Podmienky obchodnej verejnej súťaže (2 podskupiny, druhá podskupina má jednu podmienku naviac).",
            "K členeniu sme spracovali dokument, ktorý zahŕňa jednotlivé časti dokumentov.",
        ],
        actions: [
            { task: "Nájsť versatilný spôsob chunkovania dokumentov", owner: "Martin, Matúš", due: "2025-10-19", status: "open" },
            { task: "Získať od vedúcich prístup k VPS + setup VPS", owner: "Cyril, Matúš", due: "2025-10-14", status: "open" },
            { task: "Vytoriť základný backend s pripojením na databázu (stĺpec s vektorovými embeddingami)", owner: "Adam", due: "2025-10-19", status: "open" },
            { task: "Otestovať spôsoby chunkovania dokumentov.", owner: "Matúš", due: "2025-10-26", status: "open" },
            { task: "Vytvoriť GitHub repozitár pre projekt (Docker, Backend, Frontend)", owner: "Cyril", due: "2025-10-26", status: "open" },
            { task: "Základný projekt pre frontend a návrh UI", owner: "Alex", due: "2025-10-21", status: "open" },
            { task: "Dodať web stránku s projektovou dokumentáciou", owner: "Matúš, Cyril", due: "2025-10-12", status: "done" },
        ],
        previousTasksReview: [
            { owner: "Cyril", task: "Vytvoriť WWW stránku s dokumenáciou a zápisnicami", status: "in-progress", notes: "Čiastočná implementácia, nasadená bude keď bude v použiteľnom stave." },
            { owner: "Matúš, Martin", task: "Návrh technologického stacku pre vývoj AI časti - využijeme Python a vhodné knižnice, podľa potreby.", status: "done" },
            { owner: "Alexander", task: "Návrh technologického stacku pre vývoj frontendu - Frontent bude implementovaný vo frameworku React", status: "done" },
        ],
    },
];

export default MEETINGS;