const MEETINGS = [
    {
        id: "2025-09-24-kickoff",
        type: "brief",
        title: "Kick-off meeting",
        date: "2025-09-24",
        startTime: "15:00",
        endTime: "16:00",
        location: "PwC Offices",
        recorder: "Cyril Beňačka",
        attendees: [
            "Cyril Beňačka",
            "Matúš Bednařík",
            "Alexander Hulla",
            "Adam Jánoš",
            "Adam Kňaze",
            "Júlia Miklošovičová",
            "Patrícia Torok",
        ],
        agenda: [
            { topic: "Špecifikácia zadania", summary: "Prejsť s vedúcimi zadanie a vyriešiť nejasnosti." },
            { topic: "Organizácia projektu", summary: "Dohodnúť sa na nasledujúcom postupe a začiatku práce." },
        ],
        decisions: [
            "Použijeme Jiru na projektové plánovanie a GitHub pre správu kódov.",
            "Budeme využívať agilný vývoj.",
            "Dĺžka sprintu: 2 týždne.",
        ],
        actions: [
            { task: "Založiť prostredie na organizáciu projektového plánovania a projekt v ňom", owner: "Cyril", due: "2025-09-29", status: "done" },
            { task: "Vytvoriť kanál v MS teams na komunikáciu s vedúcimi", owner: "Cyril", due: "2025-09-29", status: "done" },
            { task: "Dodať vzorové dokumenty", owner: "Patrícia", due: "2025-10-08", status: "done" },
            { task: "Vytvoriť WWW stránku s dokumenáciou a zápisnicami", owner: "Cyril", due: "2025-10-10", status: "done" },
            { task: "Návrh technologického stacku pre vývoj AI časti", owner: "Martin, Matúš", due: "2025-10-17", status: "done" },
            { task: "Návrh technologického stacku pre vývoj backendu", owner: "Adam J.", due: "2025-10-17", status: "done" },
            { task: "Návrh technologického stacku pre vývoj frontendu", owner: "Alexander", due: "2025-10-17", status: "done" },
        ],
        previousTasksReview: [],
    },
    {
        id: "2025-10-08-vzorove-dokumenty",
        type: "brief",
        title: "Vzorové dokumenty",
        date: "2025-10-08",
        startTime: "14:15",
        endTime: "14:45",
        location: "MS Teams",
        recorder: "Cyril Beňačka",
        attendees: [
            "Cyril Beňačka",
            "Matúš Bednařík",
            "Patrícia Torok",
        ],
        agenda: [
            { topic: "Vzorové dokumenty", summary: "Prevziať vzorové dokumenty od vedúcich." },
        ],
        decisions: [
            "Prevzaté dokumenty budeme musieť manuálne analyzovať a uistiť sa, že sú jedného typu. Následne ich rozdelíme do podskupín podľa štruktúry ich obsahu.",
        ],
        actions: [
            { task: "Analyzovať vzorové dokumenty", owner: "Martin, Matúš, Alex, Adam", due: "2025-10-10", status: "done" },
        ],
        previousTasksReview: [
            { owner: "Cyril", task: "Vytvoriť WWW stránku s dokumenáciou a zápisnicami", status: "done", notes: "Nasadené na VPS." },
            { owner: "Cyril", task: "Vytvoriť kanál v MS teams na komunikáciu s vedúcimi", status: "done", notes: "Vytvorený kanál v MS Teams, overili sme, že všetci majú prístup." },
            { owner: "Patrícia", task: "Dodať vzorové dokumenty", status: "done", notes: "Dodaných 11 dokumentov." },
            { owner: "Cyril", task: "Vytvoriť WWW stránku s dokumenáciou a zápisnicami", status: "in-progress", notes: "Čiastočná implementácia, nasadená bude keď bude v použiteľnom stave." },
            { owner: "Matúš, Martin", task: "Návrh technologického stacku pre vývoj AI časti", status: "in-progress" },
            { owner: "Adam J.", task: "Návrh technologického stacku pre vývoj backendu", status: "done", notes: "Backend bude vyvíjaný v Pythone, konkrétne FastAPI, kvôli jednoduchému prepojeniu s AI komponentami." },
            { owner: "Alexander", task: "Návrh technologického stacku pre vývoj frontendu", status: "in-progress" },
        ],
    },
    {
        id: "2025-10-10-analyza-dokumentov",
        type: "brief",
        title: "Analýza dokumentov",
        date: "2025-10-10",
        startTime: "11:30",
        endTime: "13:00",
        location: "Unispace FEI STU + Discord",
        recorder: "Cyril Beňačka",
        attendees: [
            "Martin Bartoš",
            "Cyril Beňačka",
            "Matúš Bednařík",
            "Alexander Hulla",
        ],
        agenda: [
            { topic: "Analýza dokumentov", summary: "Prejsť štruktúru vzorových dokumentov." },
            { topic: "Organizácia projektu", summary: "Navrhnúť nasledujúci postup vývoja." },
        ],
        decisions: [
            "Dospeli sme k záveru, že ide o jeden typ dokumentov.",
            "Našli sme 2 základné skupiny: OVS - obchodná verejná súťaž, Podmienky obchodnej verejnej súťaže (2 podskupiny, druhá podskupina má jednu podmienku naviac).",
            "K členeniu sme spracovali dokument, ktorý zahŕňa jednotlivé časti dokumentov.",
        ],
        actions: [
            { task: "Nájsť versatilný spôsob chunkovania dokumentov", owner: "Martin, Matúš", due: "2025-10-19", status: "done" },
            { task: "Získať od vedúcich prístup k VPS + setup VPS", owner: "Cyril, Matúš", due: "2025-10-14", status: "done" },
            { task: "Vytoriť základný backend s pripojením na databázu (stĺpec s vektorovými embeddingami)", owner: "Adam", due: "2025-10-19", status: "done" },
            { task: "Otestovať spôsoby chunkovania dokumentov.", owner: "Matúš", due: "2025-10-26", status: "done" },
            { task: "Vytvoriť GitHub repozitár pre projekt (Docker, Backend, Frontend)", owner: "Cyril", due: "2025-10-26", status: "open" },
            { task: "Základný projekt pre frontend a návrh UI", owner: "Alex", due: "2025-10-21", status: "done" },
            { task: "Dodať web stránku s projektovou dokumentáciou", owner: "Matúš, Cyril", due: "2025-10-12", status: "done" },
        ],
        previousTasksReview: [
            { owner: "Cyril", task: "Vytvoriť WWW stránku s dokumenáciou a zápisnicami", status: "in-progress", notes: "Čiastočná implementácia, nasadená bude keď bude v použiteľnom stave." },
            { owner: "Matúš, Martin", task: "Návrh technologického stacku pre vývoj AI časti - využijeme Python a vhodné knižnice, podľa potreby.", status: "done" },
            { owner: "Alexander", task: "Návrh technologického stacku pre vývoj frontendu - Frontent bude implementovaný vo frameworku React", status: "done" },
        ],
    },
    {
        id: "2025-10-20-backend-chunking",
        type: "brief",
        title: "Vektorové databázy a chunking",
        date: "2025-10-20",
        startTime: "16:00",
        endTime: "17:00",
        location: "Discord",
        recorder: "Cyril Beňačka",
        attendees: [
            "Martin Bartoš",
            "Cyril Beňačka",
            "Matúš Bednařík",
            "Alexander Hulla",
            "Adam Jánoš"
        ],
        agenda: [
            { topic: "Backend pre vektorové databázy", summary: "Prejsť výsledky Adamovej práce." },
            { topic: "Chunking dokumentov", summary: "Prejsť výsledky Matúšovej a Martinovej práce." },
        ],
        decisions: [
            "Na účely vektorovej databázy, aspoň zo začiatku, použijeme ChromaDB. Je jednoduchá na pochopenie a nastavenie.",
            "Vypracovali sme konkrétny postup, akým sa budú chunkovať dokumenty.",
            "Využijeme sémantický chunking a Langchain knižnicu."
        ],
        actions: [

        ],
        previousTasksReview: [
            { owner: "Cyril", task: "Vytvoriť WWW stránku s dokumenáciou a zápisnicami", status: "done", notes: "Stránka bola nasadená a dodaná." },
            { owner: "Martin, Matúš", task: "Nájsť versatilný spôsob chunkovania dokumentov", status: "done" },
            { task: "Vytoriť základný backend s pripojením na databázu (stĺpec s vektorovými embeddingami)", owner: "Adam", status: "in-progress", notes: "Je nutné ho presne implementovať a nasadiť." },
            { task: "Získať od vedúcich prístup k VPS + setup VPS", owner: "Cyril, Matúš", status: "in-progress" },
            { task: "Otestovať spôsoby chunkovania dokumentov.", owner: "Matúš", status: "in-progress" },
            { task: "Vytvoriť GitHub repozitár pre projekt (Docker, Backend, Frontend)", owner: "Cyril", status: "in-progress" },
            { task: "Základný projekt pre frontend a návrh UI", owner: "Alex", status: "in-progress", notes: "Zmena termínu na 23.10." },
            { task: "Dodať web stránku s projektovou dokumentáciou", owner: "Matúš, Cyril", status: "done", notes: "Stránku sme odoslali na mail." },
        ],
    },
    {
        id: "2025-10-29-standup",
        type: "brief",
        title: "Stand-up meeting",
        date: "2025-10-29",
        startTime: "11:40",
        endTime: "12:20",
        location: "Unispace FEI STU + Discord",
        recorder: "Cyril Beňačka",
        attendees: [
            "Martin Bartoš",
            "Cyril Beňačka",
            "Matúš Bednařík",
            "Alexander Hulla",
            "Adam Jánoš"
        ],
        agenda: [
            { topic: "Stand-up meeting", summary: "Prejsť výsledky našej práce, zhodnotiť čo nás blokuje a určiť na čom budeme pracovať do nasledujúceho meetingu." },
        ],
        decisions: [
            "Budeme pokračovať v práci na implementácii frontendu.",
            "Budeme pracovať na ďalších možnostiach chunkingu dokumentov.",
            "Vytvoríme základné endpointy na backende.",
            "Integrujeme jednotlivé časti do jednotného projektu."
        ],
        actions: [
            { task: "Príprava pre CRUD operácie na frontende", owner: "Alex", due: "2025-11-4", status: "done" },
            { task: "Frontend - vytváranie projektov", owner: "Alex", due: "2025-11-4", status: "done" },
            { task: "Dizajn chatu", owner: "Alex", due: "2025-11-4", status: "done" },
            { task: "Nájsť vhodnejší spôsob chunkovania", owner: "Matúš", due: "2025-11-4", status: "done" },
            { task: "Integrácia OpenAI API kľúča", owner: "Matúš", due: "2025-11-4", status: "done" },
            { task: "Vytvoriť základnú architektúru backendu", owner: "Adam", due: "2025-11-4", status: "done" },
            { task: "Implementovať základné API endpointy", owner: "Adam", due: "2025-11-4", status: "done" },
            { task: "Nájsť vhodnejší spôsob chunkovania", owner: "Martin", due: "2025-11-4", status: "done" },
        ],
        previousTasksReview: [
            { task: "Vytoriť základný backend s pripojením na databázu (stĺpec s vektorovými embeddingami)", owner: "Adam", status: "done" },
            { task: "Získať od vedúcich prístup k VPS + setup VPS", owner: "Cyril, Matúš", status: "done", notes: "Prístup k VPS nám v PwC nie sú schopní poskytnúť, stačí to mať lokálne a následne odprezentovať." },
            { task: "Otestovať spôsoby chunkovania dokumentov.", owner: "Matúš", status: "done" },
            { task: "Vytvoriť GitHub repozitár pre projekt (Docker, Backend, Frontend)", owner: "Cyril", status: "in-progress" },
            { task: "Základný projekt pre frontend a návrh UI", owner: "Alex", status: "done" },
        ],
    },
    {
        id: "2025-11-05-standup",
        type: "brief",
        title: "Stand-up meeting",
        date: "2025-11-05",
        startTime: "11:40",
        endTime: "12:20",
        location: "Unispace FEI STU + Discord",
        recorder: "Matúš Bednařík, Cyril Beňačka",
        attendees: [
            "Martin Bartoš",
            "Matúš Bednařík",
            "Alexander Hulla",
            "Adam Jánoš",
        ],
        agenda: [
            { topic: "Status členov tímu", summary: "Prejsť, čo kto spravil od posledného stretnutia a čo ho blokuje." },
            { topic: "GitHub a Docker infraštruktúra", summary: "Zhrnutie pre nový repozitár a dockerizáciu." },
            { topic: "AI a chunking", summary: "Rozdelenie zodpovedností za chunkovanie a LLM agenta." },
        ],
        decisions: [
            "Hľadanie lepšieho spôsobu chunkovania dokumentov preberá primárne Martin, Matúš sa sústredí na LLM agenta, ktorý spája chunky.",
            "Adam bude pripravovať prompty a analýzu kvality chunkov s ohľadom na generovanie draftu.",
            "Alex zosynchronizuje frontendové požiadavky s backendom (Adam).",
        ],
        actions: [
            {
                task: "Spraviť zápisnicu zo stretnutia, doplniť ju na projektovú stránku",
                owner: "Cyril",
                due: "2025-11-12",
                status: "done",
            },
            {
                task: "Zosynchronizovať sa s Adamom ohľadom potrebných endpointov a dát pre frontend",
                owner: "Alex",
                due: "2025-11-12",
                status: "done",
            },
            {
                task: "Pripraviť nového LLM agenta, ktorý spája chunky do súvislého textu",
                owner: "Matúš",
                due: "2025-11-12",
                status: "done",
            },
            {
                task: "Navrhnúť a otestovať prompty pre generovanie draftu dokumentu",
                owner: "Martin",
                due: "2025-11-12",
                status: "in-progress",
            },
            {
                task: "Analyzovať, či sú aktuálne chunky dostatočné a vhodné pre generovanie draftu",
                owner: "Martin",
                due: "2025-11-12",
                status: "in-progress",
            },
        ],
        previousTasksReview: [
            {
                owner: "Cyril",
                task: "Vytvoriť GitHub repozitár pre projekt (Docker, Backend, Frontend)",
                status: "done",
                notes: "Založený repozitár, spravená základná dockerizácia a integrácia existujúcich častí.",
            },
            {
                owner: "Cyril",
                task: "Vytvoriť WWW stránku s dokumenáciou a zápisnicami",
                status: "done",
                notes: "Stránka existuje, zápisnice budú priebežne dopĺňané.",
            },
            {
                owner: "Alex",
                task: "Príprava pre CRUD operácie na frontende, vytváranie projektov a chatov, dizajn chatu",
                status: "done",
                notes: "Základná funkcionalita na vytváranie projektov/chatov je implementovaná, dizajn chatu pripravený.",
            },
            {
                owner: "Matúš",
                task: "Riešenie integrácie AI, frontendu a backendu do Dockeru",
                status: "done",
                notes: "Pripravená docker integrácia jednotlivých častí, čaká sa na OpenAI kľúč.",
            },
            {
                owner: "Matúš, Martin",
                task: "Nájsť vhodnejší spôsob chunkovania",
                status: "done",
            },
            {
                owner: "Adam",
                task: "Vytvoriť základnú architektúru backendu a základné API endpointy",
                status: "done",
            },
        ],
    },
    {
        id: "2025-11-12-konzultacia-llm",
        type: "brief",
        title: "Konzultácia s vedúcimi – LLM, náklady a chunking",
        date: "2025-11-12",
        startTime: "11:30",
        endTime: "12:45",
        location: "Unispace FEI STU + Teams + Discord",
        recorder: "Cyril Beňačka",
        attendees: [
            "Martin Bartoš",
            "Cyril Beňačka",
            "Matúš Bednařík",
            "Alexander Hulla",
            "Adam Jánoš",
            "Júlia Miklošovičová",
            "Patrícia Torok",
        ],
        agenda: [
            { topic: "Náklady na generovanie draftu", summary: "Overiť očakávania na dĺžku draftu a finančné limity pri použití LLM." },
            { topic: "Výber LLM modelu", summary: "Diskutovať vhodný model (OpenAI, Anthropic, iné) pre generovanie draftu." },
            { topic: "Chunking a reranking", summary: "Prebrať aktuálny prístup k chunkovaniu a možnosti využitia LangChainu a rerankerov." },
            { topic: "Technická integrácia", summary: "Bedrock Cohere reranker, Botocore integrácia, AI agent a human-in-the-loop." },
        ],
        decisions: [
            "Limitovanie vstupu/výstupu na úrovni 7 strán nie je nutné, relevantný je skôr limit ~100000 tokenov za minútu.",
            "Ako základné možnosti pre generovanie draftu budeme ďalej zvažovať Anthropic Claude (odporúčanie Júlie) a modely od OpenAI (odporúčanie Patrície).",
            "Aktuálny prístup k chunkovaniu je akceptovateľný, ale odporúča sa otestovať a integrovať LangChain (splittery, lepšia práca so štruktúrou dokumentov).",
            "Bedrock Cohere 3.5 reranker nefungoval v aktuálnej integrácii, ďalším krokom je správne pripájanie cez Botocore knižnicu.",
            "Budeme posilňovať human-in-the-loop prístup – užívateľ bude môcť lepšie usmerňovať LLM a pracovať s draftom iteratívne.",
        ],
        actions: [
            {
                task: "Spraviť zápisnicu zo stretnutia, doplniť ju na projektovú stránku",
                owner: "Cyril",
                due: "2025-11-19",
                status: "done",
            },
            {
                task: "Navrhnúť úpravy dizajnu frontendu podľa dohody",
                owner: "Cyril",
                due: "2025-11-19",
                status: "done",
            },
            {
                task: "Pomôcť tímu s rozbehaním Docker prostredia na lokálnych strojoch",
                owner: "Cyril",
                due: "2025-11-19",
                status: "in-progress",
            },
            {
                task: "Pripraviť detailnejší dizajn chat stránky, menu a súvisiacich komponentov",
                owner: "Alex",
                due: "2025-11-19",
                status: "in-progress",
            },
            {
                task: "Dokončiť návrh databázy a špecifikáciu potrebných backend endpointov",
                owner: "Alex",
                due: "2025-11-19",
                status: "in-progress",
            },
            {
                task: "Odstrániť technické limitácie LLM (prompting, nastavenia) a rozšíriť human-in-the-loop interakciu s chatbotom",
                owner: "Matúš",
                due: "2025-11-19",
                status: "in-progress",
            },
            {
                task: "Integrovať Bedrock Cohere pomocou Botocore knižnice a experimentovať s rerankingom",
                owner: "Matúš",
                due: "2025-11-26",
                status: "done",
            },
            {
                task: "Pracovať na autentifikácii a pripraviť backend endpointy podľa dokumentácie od Alexa",
                owner: "Adam",
                due: "2025-11-19",
                status: "done",
            },
            {
                task: "Pokračovať vo vizualizácii vektorových embeddingov (PCA, t-SNE, UMAP) a posúdiť kvalitu chunkovania",
                owner: "Martin",
                due: "2025-11-19",
                status: "in-progress",
            },
            {
                task: "Integrovať LangChain splitters a structured output do AI pipeline",
                owner: "Martin",
                due: "2025-11-26",
                status: "in-progress",
            },
        ],
        previousTasksReview: [
            {
                owner: "Cyril",
                task: "Zápisnica",
                status: "done",
            },
            {
                owner: "Alex",
                task: "Zosynchronizovať sa s Adamom ohľadom potrebných endpointov a dát pre frontend",
                status: "done",
                notes: "Rozbehal lokálne Docker, mergol svoje zmeny do nového repozitára, pripravil návrh databázy a analýzu endpointov.",
            },
            {
                owner: "Matúš",
                task: "Pripraviť nového LLM agenta, ktorý spája chunky do súvislého textu",
                status: "done",
                notes: "LLM agent implementovaný, potrebné bude ho ďalej vylepšovať a integrovať s human-in-the-loop.",
            },
            {
                owner: "Martin",
                task: "Experimentovať s LangChain a rôznymi spôsobmi chunkovania dokumentov",
                status: "in-progress",
                notes: "Experimentoval s chunkovaním (Chonky, LangChain) a začal pracovať na vizualizácii embeddingov.",
            },
        ],
    },
    {
        id: "2025-11-21-standup",
        type: "brief",
        title: "Stand-up meeting",
        date: "2025-11-21",
        startTime: "11:30",
        endTime: "12:00",
        location: "Unispace FEI STU",
        recorder: "Cyril Beňačka",
        attendees: [
            "Cyril Beňačka",
            "Alexander Hulla",
            "Matúš Bednařík",
            "Adam Jánoš",
            "Martin Bartoš",
        ],
        agenda: [
            {
                topic: "Stand-up meeting",
                summary: "Prejsť výsledky práce od posledného stretnutia, blokery a plán do ďalšieho stand-upu.",
            },
        ],
        decisions: [
            "Priorita je zdokonalenie frontendu (najmä chat projektu) a dokončenie sidebaru + profil/settings.",
            "Backend bude pokračovať v implementácii endpointov podľa špecifikácie z frontendu.",
            "AI časť sa sústredí na rozšírenie human-in-the-loop a optimalizáciu rýchlosti generovania, zároveň pokračuje hľadanie ideálneho chunkovania a vizualizácie embeddingov.",
        ],
        actions: [
            {
                task: "Zdokonaliť frontend (hlavne stránku chatu projektu)",
                owner: "Cyril",
                due: "2025-11-28",
                status: "open",
            },
            {
                task: "Zergovať vyvinuté časti do main vetvy",
                owner: "Cyril",
                due: "2025-11-28",
                status: "open",
            },
            {
                task: "Dokončiť sidebar + user profile + settings",
                owner: "Alex",
                due: "2025-11-28",
                status: "open",
            },
            {
                task: "Rozšíriť human-in-the-loop interakciu s chatbotom",
                owner: "Matúš",
                due: "2025-11-28",
                status: "open",
            },
            {
                task: "Optimalizovať rýchlosť generovania (zrýchlenie pipeline)",
                owner: "Matúš",
                due: "2025-11-28",
                status: "open",
            },
            {
                task: "Implementovať backend endpointy podľa špecifikácie od Alexa",
                owner: "Adam",
                due: "2025-11-28",
                status: "open",
            },
            {
                task: "Pokračovať v hľadaní ideálneho chunkovania dokumentov",
                owner: "Martin",
                due: "2025-11-28",
                status: "open",
            },
            {
                task: "Pokračovať vo vizualizácii embeddingov a posúdení kvality chunkovania",
                owner: "Martin",
                due: "2025-11-28",
                status: "open",
            },
        ],
        previousTasksReview: [
            {
                owner: "Cyril",
                task: "Dizajnové úpravy frontendu (autentifikácia, dark mode)",
                status: "done",
            },
            {
                owner: "Alex",
                task: "Práca na sidebare",
                status: "in-progress",
            },
            {
                owner: "Matúš",
                task: "Rozbehanie Bedrock Cohere (cez API) + nový ingestion skript (JSON kostra dokumentov/sekcií)",
                status: "done",
                notes: "Botocore integrácia nebola použitá; prístup riešený cez API. Kostra dokumentu (JSON) sa využíva pri dopĺňaní sekcií.",
            },
            {
                owner: "Adam",
                task: "Backend autentifikácia",
                status: "done",
            },
            {
                owner: "Martin",
                task: "Analýza structured output (LangChain) + manuálne posúdenie chunkov",
                status: "in-progress",
            },
            {
                owner: "Martin",
                task: "Rozbehanie Dockeru",
                status: "in-progress",
            },
        ],
    }
];

export default MEETINGS;